image_width: 1080
image_height: 1080
camera_name: decklink
camera_matrix:
  rows: 3
  cols: 3
  data: [698.3173 ,   0.     , 520.08321,
           0.     , 699.29715, 540.26488,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob  # by default camera_model -> change to distortion_model
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.412782, 0.198911, 0.000697, -0.001679, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [570.96423,   0.     , 515.39638,   0.     ,
           0.     , 573.93469, 541.04914,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
