image_width: 1080
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 651.69681,    0.     ,  531.86403,
            0.     ,  651.65529,  543.07064,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.394115, 0.153710, 0.000087, -0.000295, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 506.00739,    0.     ,  531.9686 ,    0.     ,
            0.     ,  506.23679,  543.03707,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
